### ISSUE TITLE
installation issue 

### ISSUE THREAD

**Issue by Neeraj-Nec** [FIWARE/tutorials.NGSI-LD#12]
Hi ,

I am getting the following issue while installing setup with Scorpio broker .

Template parsing error: template: :1:8: executing "" at <.State.Health.Status>: map has no entry for key "Health"
./services: line 90: [: ==: unary operator expected
Template parsing error: template: :1:8: executing "" at <.State.Health.Status>: map has no entry for key "Health"
./services: line 90: [: ==: unary operator expected
Template parsing error: template: :1:8: executing "" at <.State.Health.Status>: map has no entry for key "Health"
./services: line 90: [: ==: unary operator expected
Template parsing error: template: :1:8: executing "" at <.State.Health.Status>: map has no entry for key "Health"
./services: line 90: [: ==: unary operator expected
Template parsing error: template: :1:8: executing "" at <.State.Health.Status>: map has no entry for key "Health"
./services: line 90: [: ==: unary operator expected
Template parsing error: template: :1:8: executing "" at <.State.Health.Status>: map has no entry for key "Health"
./services: line 90: [: ==: unary operator expected
Template parsing error: template: :1:8: executing "" at <.State.Health.Status>: map has no entry for key "Health"
./services: line 90: [: ==: unary operator expected
Template parsing error: template: :1:8: executing "" at <.State.Health.Status>: map has no entry for key "Health"
./services: line 90: [: ==: unary operator expected
Template parsing error: template: :1:8: executing "" at <.State.Health.Status>: map has no entry for key "Health"
./services: line 90: [: ==: unary operator expected
Template parsing error: template: :1:8: executing "" at <.State.Health.Status>: map has no entry for key "Health"
./services: line 90: [: ==: unary operator expected
Template parsing error: template: :1:8: executing "" at <.State.Health.Status>: map has no entry for key "Health"
./services: line 90: [: ==: unary operator expected
Template parsing error: template: :1:8: executing "" at <.State.Health.Status>: map has no entry for key "Health"
./services: line 90: [: ==: unary operator expected
Template parsing error: template: :1:8: executing "" at <.State.Health.Status>: map has no entry for key "Health"
./services: line 90: [: ==: unary operator expected
Template parsing error: template: :1:8: executing "" at <.State.Health.Status>: map has no entry for key "Health"
./services: line 90: [: ==: unary operator expected
Template parsing error: template: :1:8: executing "" at <.State.Health.Status>: map has no entry for key "Health"
./services: line 90: [: ==: unary operator expected
Template parsing error: template: :1:8: executing "" at <.State.Health.Status>: map has no entry for key "Health"
./services: line 90: [: ==: unary operator expected
Template parsing error: template: :1:8: executing "" at <.State.Health.Status>: map has no entry for key "Health"
./services: line 90: [: ==: unary operator expected
Template parsing error: template: :1:8: executing "" at <.State.Health.Status>: map has no entry for key "Health"
./services: line 90: [: ==: unary operator expected
Template parsing error: template: :1:8: executing "" at <.State.Health.Status>: map has no entry for key "Health"
./services: line 90: [: ==: unary operator expected

my docker-compose version is 1.29.2

Please help to resolve this issue

**Comment by jason-fox** [comment]
On which specific tutorial are you getting this issue?

**Comment by Neeraj-Nec** [comment]
While running
./service scorpio

**Comment by jason-fox** [comment]
From which folder? There are lots of different tutorial repos.

**Comment by RupamNEC** [comment]
hi,
I am facing this issue from the below repo:
https://github.com/FIWARE/tutorials.IoT-Agent/tree/NGSI-LD

**Comment by jason-fox** [comment]
Your issue is a lack of a `HEALTHCHECK` in the underlying `Dockerfile`. I am unable to reproduce. Just to check you have the latest code base try the following:


```console
cd tutorials.IoT-Agent
git status
git log -1
```

Should return the following:

```text
On branch NGSI-LD
Your branch is up to date with 'origin/NGSI-LD'.

commit aafbf8c6f981d154a792c70052291fbef652480c (HEAD -> NGSI-LD, origin/NGSI-LD)
Author: Jason Fox <jason.fox@fiware.org>
Date:   Fri Jan 7 16:22:45 2022 +0100

    Update Orion
```

If not you may need to change branch or `git pull`.

Scorpio's [`HEALTHCHECK`](https://github.com/FIWARE/tutorials.IoT-Agent/blob/NGSI-LD/docker-compose/scorpio-aaio.yml#L58-L59) can be clearly seen in the `scorpio-aaio.yml`.

If you open another tab and run `docker ps` - you should see `(healthy)` next to  the `scorpiobroker` container.

```text
CONTAINER ID   IMAGE                                      COMMAND                  CREATED          STATUS                    PORTS                                                      NAMES
6d9d82b40dea   scorpiobroker/scorpio:scorpio-aaio_1.1.0   "/bin/sh -c 'bash ./…"   53 minutes ago   Up 53 minutes (healthy)   0.0.0.0:9090->9090/tcp                                     fiware-scorpio
4c5d458a3017   wurstmeister/kafka                         "start-kafka.sh"         53 minutes ago   Up 53 minutes             0.0.0.0:63101->9092/tcp                                    kafka
f7a3b5d340c5   fiware/iotagent-ul:1.19.0-distroless       "/nodejs/bin/node ./…"   53 minutes ago   Up 53 minutes (healthy)   0.0.0.0:4041->4041/tcp, 0.0.0.0:7896->7896/tcp, 4061/tcp   fiware-iot-agent
ffed1d4211b9   fiware/tutorials.ngsi-ld                   "/nodejs/bin/node ./…"   53 minutes ago   Up 53 minutes (healthy)   0.0.0.0:3000-3001->3000-3001/tcp                           fiware-tutorial
69003b56b100   mongo:4.4                                  "docker-entrypoint.s…"   53 minutes ago   Up 53 minutes (healthy)   0.0.0.0:27017->27017/tcp                                   db-mongo
c0462485102e   httpd:alpine                               "httpd-foreground"       53 minutes ago   Up 53 minutes (healthy)   0.0.0.0:3004->80/tcp                                       fiware-ld-context
15172b06ab3a   zookeeper                                  "/docker-entrypoint.…"   53 minutes ago   Up 53 minutes             2888/tcp, 3888/tcp, 8080/tcp, 0.0.0.0:63100->2181/tcp      zookeeper
5ff8e04da714   mdillon/postgis                            "docker-entrypoint.s…"   53 minutes ago   Up 53 minutes             0.0.0.0:63099->5432/tcp                                    db-postgres
```

**Comment by jason-fox** [comment]
Stale - unable to reproduce. Closing.
