### ISSUE TITLE
"Understanding @Context" section doesn't include setup information

### ISSUE THREAD

**Issue by hadjian** [FIWARE/tutorials.NGSI-LD#15]
I am working through the "step-by-step" tutorial. The section "Start Up" on this [page ](https://ngsi-ld-tutorials.readthedocs.io/en/latest/understanding-%40context.html) doesn't include any instructions, where to get the code from.

I compared this with the NGSI-v2 tutorial, where the instructions tell the reader to clone a repo and run the docker-compose.

**Comment by nikosft** [comment]
You have to clone the tutorials repository (https://github.com/FIWARE/tutorials.NGSI-LD) Then, what you need for the "understanding context" section is located in the  `tutorials.Understanding-At-Context` folder.

**Comment by jason-fox** [comment]
Fixed 78a6c07
