### ISSUE TITLE
"Understanding @Context" section use smart models instead of schema.org for building properties

### ISSUE THREAD

**Issue by nikosft** [FIWARE/tutorials.NGSI-LD#18]
Since the tutorial says 
>As it happens, there are existing [Smart Data Models](https://www.fiware.org/developers/smart-data-models/) for both Building and Device

I think it is more appropriate to refer to Smart Data Models context for building properties instead of schema.org For example address instead of
```
"address": "schema:address"
```
Could be
```
"address":"https://smartdatamodels.org/address"
```
I guess something similar applies to "Device"

**Comment by jason-fox** [comment]
Yes, there is nothing wrong with using `"address":"https://smartdatamodels.org/address"` - the aim in the tutorial was to indicate that multiple ontology providers could be used  in your `@context` and that you should defer to the common approach used in your domain - for example, if I were selling products in a supermarket I would probably use GS1 
 https://www.gs1.org/voc/PostalAddress instead.

Yes you can use smart-data-models.org, but the tutorials shouldn't leave the impression that this is the only ontology out there. Therefore I intend to continue using schema.org for the address attribute for now.
