### ISSUE TITLE
Use of payload with HTTP GET

### ISSUE THREAD

**Issue by nikosft** [FIWARE/tutorials.NGSI-LD#21]
In many examples, a payload is used with GET requests, [for example](https://ngsi-ld-tutorials.readthedocs.io/en/latest/concise.html#read-operations)

```
curl -G -iX GET 'http://localhost:1026/ngsi-ld/v1/entities/urn:ngsi-ld:TemperatureSensor:001' \
-H 'Link: <http://context/ngsi-context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
-d 'attrs=temperature'
```

I think this should be avoided and all data should included as query parameters. Note that according to [HTTP 1.1 RFC](https://www.rfc-editor.org/rfc/rfc7231#page-24)
>A payload within a GET request message has no defined semantics;  sending a payload body on a GET request might cause some existing implementations to reject the request

**Comment by kzangeli** [comment]
There is no payload body in the GET requests.
There's an HTTP header (Link) and that I believe is defined by JSON-LD.
But, of course, HTTP headers are always present in any HTTP request.

**Comment by nikosft** [comment]
The provided example uses a payload in the GET request. It's the

```
-d 'attrs=temperature'
```

part

**Comment by kzangeli** [comment]
Yeah, but the problem seems to be with the body:
> sending a payload body on a GET request might cause some existing implementations to reject the request

And there is no body.

You aren't seriously proposing to not have any URL parameters in a query, are you?

If you don't like it, NGSI-LD defines what we call "POST Query", where the method is POST and all query parameters go in a payload body.  Afaik, all NGSI-LD brokers implements that API endpoint.

**Comment by nikosft** [comment]
OK, now I saw that the `-G` option  puts everything specified in `-d` in URL. Sorry :(

**Comment by kzangeli** [comment]
ok, misunderstanding.
Kind of expected that :)
It was too weird :)))
