### ISSUE TITLE
Tutorial sequence is unclear

### ISSUE THREAD

**Issue by olisom** [FIWARE/tutorials.NGSI-LD#27]
The  [Temporal Operations page](https://ngsi-ld-tutorials.readthedocs.io/en/latest/short-term-history.html) states: "The tutorial activates the IoT collars for connected animals in the previous tutorial and links to the IoT-Agent tutorials page, which is inconsistent when you come from the subscriptions tutorial and have clicked on the 'Next' button at the bottom of the page.

In addition, I followed the IoT-Agent tutorial but didn't see anything that corresponded to collar activation.

**Comment by jason-fox** [comment]
>  the previous tutorial and links to the IoT-Agent tutorials page, which is inconsistent 

Text amended fafb59b 

> In addition, I followed the IoT-Agent tutorial but didn't see anything that corresponded to collar activation.

The Animal collars are anonymous devices,  see: [Provisioning a Service Group](https://ngsi-ld-tutorials.readthedocs.io/en/latest/iot-agent.html#provisioning-a-service-group). Within the Temporal Tutorial, the movement of the animals is used as a mechanism to ensure the context broker has some data with an `observedAt` and  changing values.


The animal collars are anonymously provisioned in the  [provision-devices](https://github.com/FIWARE/tutorials.Short-Term-History/blob/f25adf47769cb2dd6339fd09a65f89741afaf74c/provision-devices#L91-#L113) bash script.

```json
{
     "apikey":      "110990",
     "cbroker":     "http://orion:1026",
     "entity_type": "Device",
     "resource":    "/iot/d",
     "protocol":    "PDI-IoTA-UltraLight",
     "transport":   "HTTP",
     "timezone":    "Europe/Berlin",
     "attributes": [
        {"object_id": "bpm","type": "Integer","name": "heartRate",
        "metadata": {"unitCode": {"type": "Text","value": "5K"}}
        },
        {"object_id": "d", "name": "statusDescription", "type": "Property"},
        {"object_id": "s", "name": "status", "type": "Integer"},
        {"object_id": "gps", "name": "location", "type": "geo:point"}
      ],
      "static_attributes": [
        {"name": "description", "type":"Property", "value": "Animal Collar"},
        {"name": "category", "type":"Property", "value": ["sensor"]},
        {"name": "controlledProperty", "type": "Property", "value": ["heartRate", "location", "status"]},
        {"name": "supportedProtocol", "type": "Property", "value": ["ul20"]}
      ]
   }
```

Meaning that an call to `/iot/d?apiKey=110990` is recognised as an animal collar
