### ISSUE TITLE
Git clone command correction

### ISSUE THREAD

**Issue by kingsumos** [FIWARE/tutorials.NGSI-LD#5]
https://ngsi-ld-tutorials.readthedocs.io/en/latest/iot-agent-json.html shows:
git clone https://github.com/FIWARE/tutorials.IoT-Agent.git
should be changed to
git clone https://github.com/FIWARE/tutorials.IoT-Agent-JSON.git

But for the tutorials.IoT-Agent-JSON repository the issue was already fixed (see also https://github.com/FIWARE/tutorials.IoT-Agent-JSON/issues/3).

Given that tutorials.IoT-Agent-JSON is a submodule of tutorials.NGSI-LD, perhaps it's missing a submodule update? (i.e. point tutorials.IoT-Agent-JSON to latest version)

**Comment by kingsumos** [comment]
the link https://fiware-tutorials.readthedocs.io/en/stable/iot-agent-json/index.html shows the same issue (it's from a different repository?)

**Comment by jason-fox** [comment]
Fixed https://github.com/FIWARE/tutorials.NGSI-LD/commit/aac17f2
